{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentops.fullname" . }}-secrets
  labels:
    {{- include "agentops.labels" . | nindent 4 }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | default "change-me" | quote }}
  LANGSMITH_API_KEY: {{ .Values.secrets.langsmithApiKey | quote }}
{{- end }}
